### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by feanor21** [feanor21/SEBC#10]

**Comment by mfernest** [comment]
[Unsupported JDK installed](https://github.com/feanor21/SEBC/commit/1ae06a479c52a266d6f35cb06c3e6e7a01ca918a)

**Comment by mfernest** [comment]
[HDFS test user permissions not assigned](https://github.com/feanor21/SEBC/commit/3a78e34bbed89e8d66837f5d8e65b1a8cb374b78)
