### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by feanor21** [feanor21/SEBC#12]

**Comment by mfernest** [comment]
Did not submit `kdc.conf` file

**Comment by mfernest** [comment]
See commit [1f92643](https://github.com/feanor21/SEBC/commit/1f92643224a0a14f05d5a56ef84b5f419e190caf)

**Comment by mfernest** [comment]
Above commit comments also apply to terasort job. It's not clear whose Kerberos credential has been used to authorize the job.
