### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by feanor21** [feanor21/SEBC#9]

**Comment by mfernest** [comment]
See commit [6e203ef](https://github.com/feanor21/SEBC/commit/6e203efb4839f4c534612ee938408dac28ca1c8a)

**Comment by mfernest** [comment]
See commit [5e57a05](https://github.com/feanor21/SEBC/commit/5e57a055fa571db8b4efbba8fc073dd5669c214e)

**Comment by mfernest** [comment]
Missing `db.properties` content in `2_db.properties.md`
